tesi/urls.py
from django.conf.urls.defaults import *
from tesi.models import *


urlpatterns = patterns('tesi.views',
    (r'^$', 'index'),
    (r'^siti.kml$', 'all_kml'),
    (r'^mappa$', 'map_page'),
    (r'^conteggi$', 'sherdcount_list'),
    (r'^conteggi/statistiche$', 'sherdcount_index'),
    (r'^siti$', 'site_index'),
    (r'^siti/classifica$', 'site_score'),
    (r'^siti/data/(?P<date>\d+)$', 'site_index_at_date'),
    (r'^siti/data/(?P<date>\d+).kml$', 'site_kml_at_date'),
    (r'^siti/insediamenti$', 'context_settlements'),
    (r'^forme$', 'type_index'),
    (r'^forme/grafici$', 'type_graphs'),
    (r'^siti/(?P<site_id>\d+)/$', 'site_detail'),
    (r'^siti/(?P<site_slug>[-\w]+)$', 'site_detail_slug'),
    (r'^forme/(?P<type_id>\d+)/$', 'type_detail'),
    (r'^forme/(?P<type_slug>[-\w]+)$', 'type_detail_slug'),
    (r'^forme/(?P<type_id>\d+).kml$', 'type_kml'),
    (r'^forme/(?P<type_slug>[-\w]+).kml$', 'type_kml_slug'),
    (r'^forme/(?P<type_id>\d+)/mappa$', 'type_map_page'),
    (r'^forme/(?P<type_slug>[-\w]+)/mappa$', 'type_map_page_slug'),
    (r'^scavi/(?P<context_id>\d+)/$', 'context_detail'),
     (r'^scavi/(?P<context_id>\d+)/biblio$', 'context_bib'),
    (r'^grafico$', 'fentress_graph_page'),
    (r'^grafico_globale.png$', 'fentress_graph_image'),
    (r'^grafico_globale_siti.png$', 'fentress_graph_image_sites'),
    (r'^grafico_forme.png$', 'forms_graph_image'),
    (r'^scatterplot_forme_(?P<scatter_type>\d+)$', 'forms_scatter_image'),
    (r'^grafico_sito/(?P<site_slug>[-\w]+).png$', 'site_graph_image'),
    (r'^note/$', 'notes_index'),
    (r'^siti.json$', 'prop_geojson'),
    (r'^sites2.json$', 'prop_geojson2'),
    (r'^map_prop$', 'map_prop'),
    (r'^produzioni$', 'ware_index'),
    (r'^produzioni/(?P<ware_id>\d+)$', 'ware_detail'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib.gis import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'tesi.views.index', name='index'),
    url(r'^tesi/', include('tesi.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

tesi/models.py
from django.contrib.gis.db import models

# Create your models here.

class Site(models.Model):
    point = models.PointField(srid=4326,blank=True, null=True)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    pleiades = models.CharField(max_length=20, blank=True)
    objects = models.GeoManager()
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def _count_total(self):
        """Return total number of sherds for the site."""
        cs = self.context_set.all()
        if cs:
            total = sum(c.total for c in cs)
        else:
            total = 'm'
        return total
    total = property(_count_total)

    def _final_import_date(self):
        """Final date of ARS import at site."""

        scs = SherdCount.objects.filter(assemblage__context__site=self)
        forms_lst = [ sc.typename for sc in scs ]
        forms = set(forms_lst)
        if forms:
            try:
                final_end = max(f.end_date for f in forms if f.end_date)
            except ValueError:
                final_end = None
            try:
                final_hyp = max(f.end_hyp for f in forms if f.end_hyp)
            except ValueError:
                final_date = final_end
            else:
                final_date = max(final_end, final_hyp)
        else:
            final_date = None
        return final_date
    final_import_date = property(_final_import_date)

    def _initial_import_date(self):
        """Initial date of ARS import at site."""

        scs = SherdCount.objects.filter(assemblage__context__site=self)
        forms_lst = [ sc.typename for sc in scs ]
        forms = set(forms_lst)
        if forms:
            try:
                initial_start = min(f.start_date for f in forms if f.start_date)
            except ValueError:
                initial_start = None
            try:
                initial_hyp = min(f.start_hyp for f in forms if f.start_hyp)
            except ValueError:
                initial_date = initial_start
            else:
                initial_date = min(initial_start, initial_hyp)
        else:
            initial_date = None
        return initial_date
    initial_import_date = property(_initial_import_date)

class Production(models.Model):
    name = models.CharField(max_length=50, unique=True)
    subproduction_of = models.ForeignKey('self', blank=True, null=True)
    area = models.PolygonField(srid=4326,blank=True, null=True)
    description = models.TextField(blank=True)
    objects = models.GeoManager()

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Context(models.Model):
    EXCAVATION_CHOICES = (
        ('Ex','Excavation'),
        ('Su', 'Survey'),
        ('Sh', 'Shovel test'),
        )
    SETTLEMENT_CHOICES = (
        ('Ur', 'Urbano'),
        ('Va', 'Villa'),
        ('Ve', 'Villaggio'),
        ('Mi', 'Militare'),
        ('Co', 'Commerciale'),
        ('Ru', 'Rurale'),
        ('Se', 'Sepolcrale'),
        ('Ec', 'Ecclesiastico'),
        ('Gr', 'Grotta'),
        ('ND', 'Non definito'),
        )

    site = models.ForeignKey(Site)
    name = models.CharField(max_length=100)
    excavation = models.CharField(max_length=2, choices=EXCAVATION_CHOICES)
    start_date = models.IntegerField(blank=True, null=True)
    end_date = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True)
    biblio = models.TextField(blank=True)
    settlement = models.CharField(max_length=2, choices=SETTLEMENT_CHOICES, null=True)
    fastionline = models.CharField(max_length=100,
                                   blank=True,
                                   help_text='Do not put the entire URL here, only the site ID. If the complete URL is http://www.fastionline.org/micro_view.php?fst_cd=AIAC_2594 then the side ID is AIAC_2594.')
    objects = models.GeoManager()

    class Meta:
        ordering = ['site', 'name']

    def __unicode__(self):
        return u'%s, %s' % (self.site.name, self.name)

    def _count_total(self):
        """Return total number of sherds for the context."""
        total = sum(a.total_count for a in self.assemblage_set.all())
        return total
    total = property(_count_total)


class Assemblage(models.Model):
    name = models.CharField(max_length=50)
    context = models.ForeignKey(Context)
    start_date = models.IntegerField(blank=True, null=True)
    end_date = models.IntegerField(blank=True, null=True)
    total = models.IntegerField(blank=True, null=True)
    mni = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True)
    biblio = models.TextField(blank=True)
    objects = models.GeoManager()

    class Meta:
        ordering = ['context', 'name']
        unique_together = (('name', 'context'),)

    def __unicode__(self):
        return u'%s, %s : %s' % (self.context.site.name,
                                  self.context.name,
                                  self.name)

    def _count_total(self):
        """Return total number of sherds for the assemblage."""
        total = sum(sc.value for sc in self.sherdcount_set.all())
        return total
    total_count = property(_count_total)

class Type(models.Model):
    name = models.CharField(max_length=100, unique=True)
    subtype_of = models.ForeignKey('self', blank=True, null=True)
    start_date = models.IntegerField(blank=True, null=True)
    end_date = models.IntegerField(blank=True, null=True)
    start_hyp = models.IntegerField(blank=True, null=True)
    end_hyp = models.IntegerField(blank=True, null=True)
    productions = models.ManyToManyField(Production, blank=True, null=True)
    description = models.TextField(blank=True)
    biblio = models.TextField(blank=True)
    form = models.CharField(max_length=50)
    slug = models.SlugField(null=True, blank=True)
    objects = models.GeoManager()

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def _count_total(self):
        """Return total number of sherds for the type."""
        total = sum(sc.value for sc in self.sherdcount_set.all())
        return total
    total = property(_count_total)

    def _count_sites(self):
        """Count the total number of sites where the type is present."""

        sites = [ sc.assemblage.context.site for sc in self.sherdcount_set.all() ]
        sites = set(sites)
        return len(sites)
    total_sites = property(_count_sites)

    def at_site(self, site):
        """Return the value for form f at site s."""

        scs = SherdCount.objects.filter(typename=self).filter(assemblage__context__site=site)
        value = sum(sc.value for sc in scs)
        return value

class SherdCount(models.Model):
    """SherdCount objects represent a single type in an assemblage.

    They provide the number of sherds, the MNV or a presence boolean
    in the worst case. The best available value is chosen among the
    three for analysis and display of data."""

    mni = models.PositiveIntegerField('MNI', blank=True, null=True)
    count = models.PositiveIntegerField('Sherd count', blank=True, null=True)
    presence = models.BooleanField('Presence', default=False, help_text="True if sherd count is not provided.")

    typename = models.ForeignKey(Type, verbose_name='Form')
    assemblage = models.ForeignKey(Assemblage)
    description = models.TextField(blank=True)
    production = models.ForeignKey(Production, blank=True, null=True, verbose_name='Ware')
    objects = models.GeoManager()

    class Meta:
        ordering = ['assemblage', 'typename']
        unique_together = (('typename', 'assemblage', 'production'),)

    def __unicode__(self):
        result = u'%s, %s : ' % (self.assemblage.context.name, self.assemblage.name,)
        if self.count:
            result += u'%d ' % self.count
        if self.presence:
            result += u'presente '
        result += u'%s ' % self.typename
        if self.production:
            result += u'(%s)' % self.production
        return result

    @property
    def value(self):
        """Chooses the best available number for this sherdcount."""

        if not self.mni:
            if not self.count:
                return int(self.presence)
            else:
                return self.count
        else:
            return self.mni
 
# This is an auto-generated Django model module created by ogrinspect.
class Region(models.Model):
   id = models.FloatField(primary_key=True)
   id_vmap0 = models.FloatField()
   f_code = models.CharField(max_length=4)
   nam = models.CharField(max_length=43)
   na2 = models.CharField(max_length=1)
   na3 = models.CharField(max_length=32)
   tile_id = models.FloatField()
   fac_id = models.FloatField()
   geom = models.MultiPolygonField(srid=4326)
   objects = models.GeoManager()

   def __unicode__(self):
       return self.nam

class Empire(models.Model):
    periodo = models.IntegerField(max_length=80)
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()

class Coastline(models.Model):
    natural = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    geom = models.LineStringField(srid=4326)
    objects = models.GeoManager()

tesi/forms.py
#!/usr/bin/env python
# a stacked bar plot with errorbars

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fmg

import csv

small_font = fmg.FontProperties(size='xx-small')

def forms_graph(values, output):

    tortarray = np.array(values)

    """['Hayes 94,3' '425' '450' '500' '525' 'Bowl' 'Uncommon']"""

    N = len(tortarray)

    tortarray = tortarray[tortarray[:,2].argsort(),]

    starts = tortarray[:,2].astype('d')
    ends   = tortarray[:,3].astype('d')
    names  = tortarray[:,0]
    frequency = tortarray[:,6].astype('d')

#    forms = tortarray[:,5]

    freq_map = {
        'Rare' : 0.2,
        'Rather uncommon' : 0.4,
        'Uncommon' : 0.3,
        'Fairly common' : 0.6,
        'Common' : 0.8,
        'Rather common' : 0.5,
        'Very common' : 1.0,
        '' : 0.2
        }

    form_map = {
        'dish' : '#c90000',
        'plate' : '#00c900',
        'bowl' : '#0000c9',
        }

    for i in tortarray:
        if i[1] == '':
            i[1] = i[2]
        if i[4] == '':
            i[4] = i[3]

    min_date = tortarray[:,1].astype('d')
    max_date = tortarray[:,4].astype('d')

#    width = [ freq_map[i] for i in frequency ]
#    colors = [form_map[i.split()[-1].lower()] for i in forms ]
    ind = np.arange(N) + 1   # the x locations for the groups
    plt.figure(figsize=(12,9))
    p0 = plt.bar(ind, max_date - min_date, width=0.02, bottom=min_date, align='center', color='g', lw=0, alpha=0.3)
#    p1 = plt.bar(ind, ends - starts, width=0.6, bottom=starts, align='center', color='66b366', lw=0,)
    p1 = plt.bar(ind,
                 ends - starts,
                 width=np.log(frequency)/(ends - starts + 1)*30 + 0.1,
                 # freak viz
                 #width=frequency/(ends - starts + 1)*30 + 0.1,
                 bottom=starts,
                 align='center',
                 color='g',
                 lw=0,
                 alpha=0.5)

    plt.ylabel('Anni')
    plt.title('Cronologie ARS')
    plt.xticks(ind, names, rotation=90, fontsize=5 )
    for i in ind:
        plt.text(i, ends[i-1], names[i-1], rotation=45, fontsize=5 )
    plt.grid(ls='-', alpha=0.05)
    #plt.grid(ydata = np.array([0]), ls='-', alpha=0.2)
#    plt.legend(('dish', 'plate', 'bowl'), loc='upper left' )
    plt.savefig(output)
    fig = plt.gcf()
    fig.clear()

def forms_scatter_hard(values, output):
    tortarray = np.array(values)
    N = len(tortarray)
    tortarray = tortarray[tortarray[:,2].argsort(),]
    starts = tortarray[:,2].astype('d')
    ends   = tortarray[:,3].astype('d')
    names  = tortarray[:,0]
    forms = tortarray[:,5]
    frequency = tortarray[:,6].astype('d')

    form_map = ('#c90000', '#00c900', '#0000c9', '#c9c9c9')
    def fmap(form):
        try:
            text = form.split()[-1].lower()
            if 'dish' in text:
                return form_map[0]
            elif 'plate' in text:
                return form_map[1]
            elif 'bowl' in text:
                return form_map[2]
            else:
                return form_map[3]
        except IndexError:
            return form_map[3]
    colors = map(fmap,forms)
    fig = plt.figure()
    ax = fig.add_subplot(111)
    # ugly hack for getting a decent legend
    # f_dish = ax.scatter( starts, ends, s=np.sqrt(frequency)*20, facecolor=form_map[0], lw=0, label='Dish')
    # f_plate = ax.scatter( starts, ends, s=np.sqrt(frequency)*20, facecolor=form_map[1], lw=0, label='Plate')
    # f_bowl = ax.scatter( starts, ends, s=np.sqrt(frequency)*20, facecolor=form_map[2], lw=0, label='Bowl')
    # f_unknown = ax.scatter( starts, ends, s=np.sqrt(frequency)*20, facecolor=form_map[3], lw=0, label='Undefined')
    # fig.clear()
    # ax = fig.add_subplot(111)
#    for i in form_map:
#        ax.plot(0,0, i)
#    plt.legend(('dish', 'plate', 'bowl','unknown'), loc=2 )
    ax.scatter( starts,
                ends,
                #marker=(xy1,0),
                s=np.sqrt(frequency)*20,
                alpha=0.3,
                facecolor=colors,
                lw=0,
                #label=('Dish', 'Plate', 'Bowl', 'Undefined',)
                )

    plt.grid(ls='-', alpha=0.05)
#    for i in tortarray:
#        plt.text(i[2], i[3], i[0], fontsize=5,
#        rotation=45,
#        alpha=0.3 )
    plt.xlabel('Comparsa della forma')
    plt.ylabel('Scomparsa della forma')
    plt.title('Comparsa e scomparsa delle forme')
    # plt.legend( (f_dish, f_plate, f_bowl, f_unknown,),
    #             ('Dish', 'Plate', 'Bowl', 'Undefined',),
    #             #prop=small_font,
    #             loc=2 )
    plt.savefig(output)
    fig.clear()

def forms_scatter_simple(values, output):
    tortarray = np.array(values)
    N = len(tortarray)
    tortarray = tortarray[tortarray[:,2].argsort(),]
    starts = tortarray[:,2].astype('d')
    ends   = tortarray[:,3].astype('d')
    names  = tortarray[:,0]
    forms = tortarray[:,5]
    frequency = tortarray[:,6].astype('d')

    fig = plt.figure()
    ax = fig.add_subplot(111)

    ax.scatter( starts,
                ends,
                #marker=(xy1,0),
                s=np.sqrt(frequency)*20,
                alpha=0.3,
                facecolor='g',
                lw=0)

    plt.xlabel('Comparsa della forma')
    plt.ylabel('Scomparsa della forma')
    plt.title('Comparsa e scomparsa delle forme')
    plt.savefig(output)
    fig.clear()

tesi/templates/base.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Definire la complessità{% endblock %}</title>
    <link href="{{ STATIC_URL }}tesi.css" rel="stylesheet" type="text/css" />
    {% block head %}{% endblock %}
</head>

{% block body %}<body>{% endblock %}
<div id="header">
<p><a href="{% url tesi.views.index %}">Definire la complessità</a></p>

        <ul id="nav">
        <li><a href="{% url tesi.views.site_index %}">Siti</a></li>
        <li><a href="{% url tesi.views.map_page %}">Mappa dei siti</a></li>
        <li><a href="{% url tesi.views.sherdcount_list %}">Conteggi</a></li>
        <li><a href="{% url tesi.views.type_index %}">Forme</a></li>
        <li><a href="{% url tesi.views.fentress_graph_page %}">Grafico</a></li>
        </ul>
    <div class="clear"></div>
</div>

<div id="main">
    <div id="sidebar">
    {% block sidebar %}{% endblock %}
    </div>

    {% block content %}{% endblock %}
    {% block map %}{% endblock %}
</div>

<div id="footer">
{% block footer %}
<p>Ultimo aggiornamento {% now "d-m-Y" %}.</p>
<p>Questo sito e tutti i suoi contenuti sono pubblicati sotto una 
<span style="color: black;"><a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/it/">Licenza Creative Commons</a> Attribuisci - Condividi allo stesso modo</span>.
{% endblock %}
</div>
</body>
</html>

tesi/templates/biblio_snippet.html
<!-- fetched from Zotero - see http://www.zotero.org/support/dev/server_api/read_api -->
{% for item in biblio %}<p style="line-height: 1.35; margin-bottom: 1em; text-indent: -2em; padding-left: 2em">{{ item.biblio|removetags:"div"|safe }} ‒ <em>(see this citation on <a href="{{ item.url }}">Zotero</a>)</em></p>{% endfor %}

tesi/templates/context_detail.html
{% extends "site_base.html" %}

{% block title %}{{ context.name }}, {{ context.site }} - {{ block.super }}{% endblock %}
{% block head %}
<script language="javascript" type="text/javascript" src="{{ STATIC_URL }}jqplot/jquery.min.js"></script>
{% endblock head %}

{% block breadcrumb %}
{% spaceless %}
{{ block.super }} » <a href="{% url tesi.views.site_detail_slug context.site.slug %}">
{{ context.site }}</a> » {{ context.name }}
{% endspaceless %}
{% endblock %}


{% block index %}
<h3>Informazioni generali</h3>
<dl>
<dt>Tipo di indagine</dt>
    <dd>{{ context.get_excavation_display|default:"non specificato" }}</dd>
<dt>Tipo di insediamento</dt>
    <dd>{{ context.get_settlement_display|default:"non specificato" }}</dd>
</dl>
{% if context.fastionline %}
<p class="fastionline">Questo scavo è presente su FastiOnline (<a href="http://www.fastionline.org/micro_view.php?&fst_cd={{ context.fastionline }}">{{ context.fastionline }}</a>)</p>
{% endif %}

{% if context.description %}
<p>{{ context.description }}</p>
{% endif %}

{% if context.assemblage_set.all %}
<h3>Totale frammenti ARS</h3>
<p>{{ context.total }} esemplar{{ context.total|pluralize:"e,i" }}</p>
{% endif %}

{% if context.assemblage_set.all %}
<h3>Contesti</h3>
<table>
<tr>
    <th>Contesto</th>
    <th>Datazione</th>
    <th>Esemplari ARS</th>
    <th>Totale contesto<sup><a href="{% url tesi.views.notes_index %}#frammenti-totali">?</a></sup></th>
</tr>
{% for a in context.assemblage_set.all %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td>{{ a.name }}</td>
        <td>{{ a.start_date|default:"…" }} &ndash; {{ a.end_date|default:"…" }}</td>
        <td class="number-cell">{{ a.total_count }}</td>
        <td class="number-cell">{{ a.count|default:"assente" }}</td>
    </tr>
{% endfor %}
</table>
{% endif %}

{% if sherdcounts %}
<h3>Forme</h3>

<table>
  <tr>
    <th>Forme</th>
    {% for t in titles %}
    {% if t.total_count %}
    <th>{{ t.name }}</th>
    {% endif %}
    {% endfor %}
  </tr>
  {% for row in final %}
  <tr class="{% cycle 'row1' 'row2' %}">
      {% for cell in row %}<td>{% ifequal cell 0 %}&nbsp;{% else %}{{ cell }}{% endifequal %}</td>{% endfor %}
  </tr>
  {% endfor %}
</table>
{% endif %}

<h3 id="biblio">Riferimenti bibliografici</h3>

<div id="cites" class="bibtex">
{% if context.biblio %}
<span id="wait">Sto caricando i dati da Zotero ...</span>
<script type="text/javascript">
$('#wait').ajaxStart(function() {
    $(this).show();
}).ajaxComplete(function() {
    $(this).hide();
});
$(document).ready(function(){
    $('#cites').load('{% url tesi.views.context_bib context.id %}');
});
</script>
{% else %}
Oh no! Non c'è nessun riferimento bibliografico!
{% endif %}</div>
{% endblock index %}

tesi/templates/site_detail.html
{% extends "site_base.html" %}

{% block title %}{{ site }} - {{ block.super }}{% endblock %}

{% block head %}
<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="{{ STATIC_URL }}jqplot/excanvas.js"></script><![endif]-->
<script language="javascript" type="text/javascript" src="{{ STATIC_URL }}jqplot/jquery.min.js"></script>
<script language="javascript" type="text/javascript" src="{{ STATIC_URL }}jqplot/jquery.jqplot.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}jqplot/jquery.jqplot.css" />

<link rel="stylesheet" href="{{ STATIC_URL }}leaflet/leaflet.css" />
<!--[if lte IE 8]><link rel="stylesheet" href="{{ STATIC_URL }}leaflet/leaflet.ie.css" /><![endif]-->
{% endblock %}

{% block breadcrumb %}
{{ block.super }} » {{ site }}
{% endblock %}

{% block index %}

{% if site.description %}
<p>{{ site.description|linebreaks }}</p>
{% endif %}

<h3>Informazioni generali</h3>
<div style="float:right; height: 200px; width: 300px"" id="map"></div>
<script src="{{ STATIC_URL }}leaflet/leaflet.js"></script>
<script type="text/javascript">
// initialize the map on the "map" div with a given center and zoom 
var map = new L.Map('map', {
    center: new L.LatLng({{ site.point.y}}, {{ site.point.x }}),
    zoom: 6
});

// create a Natural Earth WMS layer
var ne2 = new L.TileLayer.WMS("http://www.catais.org/geoserver/wms?", {
    layers: 'ne2:ne2',
    format: 'image/png',
    transparent: true,
    attribution: "CatAIS Web Map Service"
});

// add the Natural Earth WMS layer to the map
map.addLayer(ne2);

var AltMarker = L.Icon.extend({
    iconUrl: '{{ STATIC_URL }}leaflet/images/marker-alt.png',
    shadowUrl: '{{ STATIC_URL }}leaflet/images/marker-shadow.png',
});

var altIcon = new AltMarker();
var markerLocation = new L.LatLng({{ site.point.y}}, {{ site.point.x }}),
    marker = new L.Marker(markerLocation, {icon: altIcon});

map.addLayer(marker);
</script>
<dl>
<dt>Totale esemplari di ARS sul sito</dt>
    <dd><strong>{{ site.total|default:"non disponibile" }}</strong></dd>
{% if site.final_import_date %}
<dt>Ultima data possibile di importazione ARS</dt>
    <dd><strong>{{ site.final_import_date }} AD</strong></dd>
{% endif %}
</dl>
{% if site.pleiades %}
<p class="pleiades">Pleiades place <a href="http://pleiades.stoa.org/places/{{ site.pleiades }}">{{ site.pleiades }}</a></p>
{% endif %}

<h3>Scavi</h3>
<ul>
{% for context in site.context_set.all %}
{% spaceless %}
<li>
    {% if context.settlement %}{% else %}(S){% endif %}
    {% if context.excavation %}{% else %}(E){% endif %}
    <a href="{% url tesi.views.context_detail context.id %}">{{ context.name }}</a> ({{ context.get_excavation_display }})
    {% if context.assemblage_set.all %}:
    {{ context.total }} esemplar{{ context.total|pluralize:"e,i" }}{% endif %}
</li>
{% endspaceless %}
{% endfor %}
</ul>

{% ifnotequal site.total 0 %}
<h3>Grafico</h3>
<div id="chartdiv" style="height:400px;width:600px; "></div>
<script type="text/javascript">
$(document).ready(function(){
    var plot1 = $.jqplot('chartdiv',[{{ graph_json }}], {
        title: 'Distribuzione cronologica complessiva: {{ site.name }}',
        seriesDefaults: { showMarker:false, color: '#28d08f' },

        axes:{
        // Let the lines start at the edge of the axis.
            xaxis:{
                ticks: [400, 450, 500, 550, 600, 650, 700] },
        },
        grid: {
            background: '#fff',
        }
      });
});
</script>
{% endifnotequal %}

{% if forms %}
<h3>Forme attestate</h3>

<table>
<tr>
    <th>Forma</th>
    <th colspan="2">Conteggio</th>
</tr>
{% for f in forms|dictsortreversed:"count" %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td><a href="{% url tesi.views.type_detail_slug f.type.slug %}">{{ f.type.name }}</a></td>
        {% ifnotequal f.count "True" %}
        <td class="number-cell">{{ f.count }}</td>
        <td><img src="{{ STATIC_URL }}bar.png" height="10" width="{{ f.count }}" /></td>
        {% else %}
        <td>presente</td>
        <td>*</td>
        {% endifnotequal %}
    </tr>
{% endfor %}
</table>
{% endif %}

{% endblock index %}